name: Generate data files

on:
  workflow_dispatch:

jobs:
  generate-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: npm
          node-version: 20

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Run Node.js script
        run: node scripts/generate-versions.mjs

      - name: Check for changes and commit
        run: |
          OUTPUT_FILE="src/data/versions.json"
          if [[ -n $(git status --porcelain $OUTPUT_FILE) ]]; then
            git config user.name "jellyfin-bot"
            git config user.email "team@jellyfin.org"
            git add $OUTPUT_FILE
            git commit -m "Update versions.json"
            git push origin master
          fi
